apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "target-app.web.fullname" . }}
  labels:
    {{- include "target-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "target-app.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "target-app.web.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "target-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: web
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        env:
        - name: MYSQL_HOST
          value: {{ include "target-app.mysql.fullname" . }}
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "target-app.fullname" . }}-mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "target-app.fullname" . }}-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "target-app.fullname" . }}-mysql-secret
              key: mysql-password
        - name: ID
          value: {{ .Values.web.env.id | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.web.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.web.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.web.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
