{{- if .Values.mysql.enabled }}
{{- if .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "target-app.mysql.fullname" . }}-pvc
  labels:
    {{- include "target-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
{{- end }}
