apiVersion: v1
kind: Secret
metadata:
  name: {{ include "target-app.fullname" . }}-mysql-secret
  labels:
    {{- include "target-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
  mysql-database: {{ .Values.mysql.auth.database | quote }}
  mysql-user: {{ .Values.mysql.auth.username | quote }}
